# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui_forms/widgets/matching_ui.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form_Matching(object):
    def setupUi(self, Form_Matching):
        Form_Matching.setObjectName("Form_Matching")
        Form_Matching.resize(800, 500)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form_Matching.sizePolicy().hasHeightForWidth())
        Form_Matching.setSizePolicy(sizePolicy)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form_Matching)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(6)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_4 = QtWidgets.QLabel(Form_Matching)
        self.label_4.setObjectName("label_4")
        self.verticalLayout_4.addWidget(self.label_4)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(-1, 0, -1, -1)
        self.horizontalLayout_3.setSpacing(5)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.periodic_solution = QtWidgets.QCheckBox(Form_Matching)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.periodic_solution.sizePolicy().hasHeightForWidth())
        self.periodic_solution.setSizePolicy(sizePolicy)
        self.periodic_solution.setMinimumSize(QtCore.QSize(140, 0))
        self.periodic_solution.setMaximumSize(QtCore.QSize(140, 16777215))
        self.periodic_solution.setObjectName("periodic_solution")
        self.horizontalLayout_3.addWidget(self.periodic_solution)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.label_23 = QtWidgets.QLabel(Form_Matching)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        spacerItem1 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout_7.addLayout(self.horizontalLayout)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setSpacing(10)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_beta_x_in = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_beta_x_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_x_in.setObjectName("lineEdit_beta_x_in")
        self.gridLayout_4.addWidget(self.lineEdit_beta_x_in, 0, 2, 1, 1)
        self.lineEdit_alpha_x_in = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_alpha_x_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_x_in.setObjectName("lineEdit_alpha_x_in")
        self.gridLayout_4.addWidget(self.lineEdit_alpha_x_in, 2, 2, 1, 1)
        self.comboBox_beta_x_in = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_beta_x_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_x_in.setObjectName("comboBox_beta_x_in")
        self.comboBox_beta_x_in.addItem("")
        self.comboBox_beta_x_in.setItemText(0, "")
        self.comboBox_beta_x_in.addItem("")
        self.comboBox_beta_x_in.addItem("")
        self.comboBox_beta_x_in.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_beta_x_in, 0, 1, 1, 1)
        self.lineEdit_beta_y_in = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_beta_y_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_y_in.setObjectName("lineEdit_beta_y_in")
        self.gridLayout_4.addWidget(self.lineEdit_beta_y_in, 1, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(Form_Matching)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(Form_Matching)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_4.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(Form_Matching)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 4, 0, 1, 1)
        self.comboBox_beta_y_in = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_beta_y_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_y_in.setObjectName("comboBox_beta_y_in")
        self.comboBox_beta_y_in.addItem("")
        self.comboBox_beta_y_in.setItemText(0, "")
        self.comboBox_beta_y_in.addItem("")
        self.comboBox_beta_y_in.addItem("")
        self.comboBox_beta_y_in.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_beta_y_in, 1, 1, 1, 1)
        self.comboBox_alpha_y_in = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_alpha_y_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_y_in.setObjectName("comboBox_alpha_y_in")
        self.comboBox_alpha_y_in.addItem("")
        self.comboBox_alpha_y_in.setItemText(0, "")
        self.comboBox_alpha_y_in.addItem("")
        self.comboBox_alpha_y_in.addItem("")
        self.comboBox_alpha_y_in.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_alpha_y_in, 3, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(Form_Matching)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_4.addWidget(self.label_6, 1, 0, 1, 1)
        self.comboBox_alpha_x_in = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_alpha_x_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_x_in.setObjectName("comboBox_alpha_x_in")
        self.comboBox_alpha_x_in.addItem("")
        self.comboBox_alpha_x_in.setItemText(0, "")
        self.comboBox_alpha_x_in.addItem("")
        self.comboBox_alpha_x_in.addItem("")
        self.comboBox_alpha_x_in.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_alpha_x_in, 2, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(Form_Matching)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 3, 0, 1, 1)
        self.lineEdit_alpha_y_in = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_alpha_y_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_y_in.setObjectName("lineEdit_alpha_y_in")
        self.gridLayout_4.addWidget(self.lineEdit_alpha_y_in, 3, 2, 1, 1)
        self.comboBox_Dx_in = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_Dx_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dx_in.setObjectName("comboBox_Dx_in")
        self.comboBox_Dx_in.addItem("")
        self.comboBox_Dx_in.setItemText(0, "")
        self.comboBox_Dx_in.addItem("")
        self.comboBox_Dx_in.addItem("")
        self.comboBox_Dx_in.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_Dx_in, 4, 1, 1, 1)
        self.lineEdit_Dx_in = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_Dx_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dx_in.setObjectName("lineEdit_Dx_in")
        self.gridLayout_4.addWidget(self.lineEdit_Dx_in, 4, 2, 1, 1)
        self.label_10 = QtWidgets.QLabel(Form_Matching)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 5, 0, 1, 1)
        self.comboBox_Dxp_in = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_Dxp_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dxp_in.setObjectName("comboBox_Dxp_in")
        self.comboBox_Dxp_in.addItem("")
        self.comboBox_Dxp_in.setItemText(0, "")
        self.comboBox_Dxp_in.addItem("")
        self.comboBox_Dxp_in.addItem("")
        self.comboBox_Dxp_in.addItem("")
        self.gridLayout_4.addWidget(self.comboBox_Dxp_in, 5, 1, 1, 1)
        self.lineEdit_Dxp_in = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_Dxp_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dxp_in.setObjectName("lineEdit_Dxp_in")
        self.gridLayout_4.addWidget(self.lineEdit_Dxp_in, 5, 2, 1, 1)
        self.verticalLayout_7.addLayout(self.gridLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout_7)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        spacerItem2 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.label_24 = QtWidgets.QLabel(Form_Matching)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_4.addWidget(self.label_24)
        spacerItem3 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem3)
        self.verticalLayout_8.addLayout(self.horizontalLayout_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setSpacing(10)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.comboBox_beta_x_out = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_beta_x_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_x_out.setObjectName("comboBox_beta_x_out")
        self.comboBox_beta_x_out.addItem("")
        self.comboBox_beta_x_out.setItemText(0, "")
        self.comboBox_beta_x_out.addItem("")
        self.comboBox_beta_x_out.addItem("")
        self.comboBox_beta_x_out.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_beta_x_out, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(Form_Matching)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 3, 0, 1, 1)
        self.comboBox_alpha_x_out = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_alpha_x_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_x_out.setObjectName("comboBox_alpha_x_out")
        self.comboBox_alpha_x_out.addItem("")
        self.comboBox_alpha_x_out.setItemText(0, "")
        self.comboBox_alpha_x_out.addItem("")
        self.comboBox_alpha_x_out.addItem("")
        self.comboBox_alpha_x_out.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_alpha_x_out, 3, 1, 1, 1)
        self.lineEdit_alpha_x_out = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_alpha_x_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_x_out.setObjectName("lineEdit_alpha_x_out")
        self.gridLayout_5.addWidget(self.lineEdit_alpha_x_out, 3, 2, 1, 1)
        self.label_11 = QtWidgets.QLabel(Form_Matching)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout_5.addWidget(self.label_11, 0, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(Form_Matching)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout_5.addWidget(self.label_12, 2, 0, 1, 1)
        self.comboBox_beta_y_out = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_beta_y_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_y_out.setObjectName("comboBox_beta_y_out")
        self.comboBox_beta_y_out.addItem("")
        self.comboBox_beta_y_out.setItemText(0, "")
        self.comboBox_beta_y_out.addItem("")
        self.comboBox_beta_y_out.addItem("")
        self.comboBox_beta_y_out.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_beta_y_out, 2, 1, 1, 1)
        self.lineEdit_beta_x_out = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_beta_x_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_x_out.setObjectName("lineEdit_beta_x_out")
        self.gridLayout_5.addWidget(self.lineEdit_beta_x_out, 0, 2, 1, 1)
        self.comboBox_Dx_out = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_Dx_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dx_out.setObjectName("comboBox_Dx_out")
        self.comboBox_Dx_out.addItem("")
        self.comboBox_Dx_out.setItemText(0, "")
        self.comboBox_Dx_out.addItem("")
        self.comboBox_Dx_out.addItem("")
        self.comboBox_Dx_out.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_Dx_out, 6, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(Form_Matching)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout_5.addWidget(self.label_15, 6, 0, 1, 1)
        self.lineEdit_beta_y_out = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_beta_y_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_y_out.setObjectName("lineEdit_beta_y_out")
        self.gridLayout_5.addWidget(self.lineEdit_beta_y_out, 2, 2, 1, 1)
        self.label_14 = QtWidgets.QLabel(Form_Matching)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout_5.addWidget(self.label_14, 5, 0, 1, 1)
        self.lineEdit_alpha_y_out = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_alpha_y_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_y_out.setObjectName("lineEdit_alpha_y_out")
        self.gridLayout_5.addWidget(self.lineEdit_alpha_y_out, 5, 2, 1, 1)
        self.comboBox_alpha_y_out = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_alpha_y_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_y_out.setObjectName("comboBox_alpha_y_out")
        self.comboBox_alpha_y_out.addItem("")
        self.comboBox_alpha_y_out.setItemText(0, "")
        self.comboBox_alpha_y_out.addItem("")
        self.comboBox_alpha_y_out.addItem("")
        self.comboBox_alpha_y_out.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_alpha_y_out, 5, 1, 1, 1)
        self.lineEdit_Dx_out = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_Dx_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dx_out.setObjectName("lineEdit_Dx_out")
        self.gridLayout_5.addWidget(self.lineEdit_Dx_out, 6, 2, 1, 1)
        self.label_16 = QtWidgets.QLabel(Form_Matching)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout_5.addWidget(self.label_16, 7, 0, 1, 1)
        self.lineEdit_Dxp_out = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_Dxp_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dxp_out.setObjectName("lineEdit_Dxp_out")
        self.gridLayout_5.addWidget(self.lineEdit_Dxp_out, 7, 2, 1, 1)
        self.comboBox_Dxp_out = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_Dxp_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dxp_out.setObjectName("comboBox_Dxp_out")
        self.comboBox_Dxp_out.addItem("")
        self.comboBox_Dxp_out.setItemText(0, "")
        self.comboBox_Dxp_out.addItem("")
        self.comboBox_Dxp_out.addItem("")
        self.comboBox_Dxp_out.addItem("")
        self.gridLayout_5.addWidget(self.comboBox_Dxp_out, 7, 1, 1, 1)
        self.verticalLayout_8.addLayout(self.gridLayout_5)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtWidgets.QVBoxLayout()
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem4 = QtWidgets.QSpacerItem(30, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem4)
        self.label_25 = QtWidgets.QLabel(Form_Matching)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_5.addWidget(self.label_25)
        spacerItem5 = QtWidgets.QSpacerItem(45, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem5)
        self.verticalLayout_9.addLayout(self.horizontalLayout_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setSpacing(10)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.comboBox_beta_x_all = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_beta_x_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_x_all.setObjectName("comboBox_beta_x_all")
        self.comboBox_beta_x_all.addItem("")
        self.comboBox_beta_x_all.setItemText(0, "")
        self.comboBox_beta_x_all.addItem("")
        self.comboBox_beta_x_all.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_beta_x_all, 0, 1, 1, 1)
        self.label_18 = QtWidgets.QLabel(Form_Matching)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout_6.addWidget(self.label_18, 1, 0, 1, 1)
        self.comboBox_alpha_y_all = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_alpha_y_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_y_all.setObjectName("comboBox_alpha_y_all")
        self.comboBox_alpha_y_all.addItem("")
        self.comboBox_alpha_y_all.setItemText(0, "")
        self.comboBox_alpha_y_all.addItem("")
        self.comboBox_alpha_y_all.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_alpha_y_all, 3, 1, 1, 1)
        self.lineEdit_beta_x_all = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_beta_x_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_x_all.setObjectName("lineEdit_beta_x_all")
        self.gridLayout_6.addWidget(self.lineEdit_beta_x_all, 0, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(Form_Matching)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_6.addWidget(self.label_17, 0, 0, 1, 1)
        self.label_19 = QtWidgets.QLabel(Form_Matching)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_6.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(Form_Matching)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 3, 0, 1, 1)
        self.lineEdit_alpha_x_all = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_alpha_x_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_x_all.setObjectName("lineEdit_alpha_x_all")
        self.gridLayout_6.addWidget(self.lineEdit_alpha_x_all, 2, 2, 1, 1)
        self.comboBox_Dx_all = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_Dx_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dx_all.setObjectName("comboBox_Dx_all")
        self.comboBox_Dx_all.addItem("")
        self.comboBox_Dx_all.setItemText(0, "")
        self.comboBox_Dx_all.addItem("")
        self.comboBox_Dx_all.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_Dx_all, 4, 1, 1, 1)
        self.lineEdit_alpha_y_all = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_alpha_y_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_y_all.setObjectName("lineEdit_alpha_y_all")
        self.gridLayout_6.addWidget(self.lineEdit_alpha_y_all, 3, 2, 1, 1)
        self.comboBox_alpha_x_all = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_alpha_x_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_x_all.setObjectName("comboBox_alpha_x_all")
        self.comboBox_alpha_x_all.addItem("")
        self.comboBox_alpha_x_all.setItemText(0, "")
        self.comboBox_alpha_x_all.addItem("")
        self.comboBox_alpha_x_all.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_alpha_x_all, 2, 1, 1, 1)
        self.lineEdit_beta_y_all = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_beta_y_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_y_all.setObjectName("lineEdit_beta_y_all")
        self.gridLayout_6.addWidget(self.lineEdit_beta_y_all, 1, 2, 1, 1)
        self.comboBox_beta_y_all = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_beta_y_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_y_all.setObjectName("comboBox_beta_y_all")
        self.comboBox_beta_y_all.addItem("")
        self.comboBox_beta_y_all.setItemText(0, "")
        self.comboBox_beta_y_all.addItem("")
        self.comboBox_beta_y_all.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_beta_y_all, 1, 1, 1, 1)
        self.label_21 = QtWidgets.QLabel(Form_Matching)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 4, 0, 1, 1)
        self.lineEdit_Dx_all = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_Dx_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dx_all.setObjectName("lineEdit_Dx_all")
        self.gridLayout_6.addWidget(self.lineEdit_Dx_all, 4, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(Form_Matching)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout_6.addWidget(self.label_22, 5, 0, 1, 1)
        self.lineEdit_Dxp_all = QtWidgets.QLineEdit(Form_Matching)
        self.lineEdit_Dxp_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dxp_all.setObjectName("lineEdit_Dxp_all")
        self.gridLayout_6.addWidget(self.lineEdit_Dxp_all, 5, 2, 1, 1)
        self.comboBox_Dxp_all = QtWidgets.QComboBox(Form_Matching)
        self.comboBox_Dxp_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dxp_all.setObjectName("comboBox_Dxp_all")
        self.comboBox_Dxp_all.addItem("")
        self.comboBox_Dxp_all.setItemText(0, "")
        self.comboBox_Dxp_all.addItem("")
        self.comboBox_Dxp_all.addItem("")
        self.gridLayout_6.addWidget(self.comboBox_Dxp_all, 5, 1, 1, 1)
        self.verticalLayout_9.addLayout(self.gridLayout_6)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setContentsMargins(-1, 0, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3.addLayout(self.gridLayout)
        self.verticalLayout_4.addLayout(self.horizontalLayout_3)
        spacerItem6 = QtWidgets.QSpacerItem(20, 80, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem6)
        self.btn2 = QtWidgets.QPushButton(Form_Matching)
        self.btn2.setObjectName("btn2")
        self.verticalLayout_4.addWidget(self.btn2)
        self.btn1 = QtWidgets.QPushButton(Form_Matching)
        self.btn1.setObjectName("btn1")
        self.verticalLayout_4.addWidget(self.btn1)
        self.label_2 = QtWidgets.QLabel(Form_Matching)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_4.addWidget(self.label_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.old_results = QtWidgets.QTextEdit(Form_Matching)
        self.old_results.setMinimumSize(QtCore.QSize(0, 0))
        self.old_results.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.old_results.setReadOnly(True)
        self.old_results.setObjectName("old_results")
        self.horizontalLayout_7.addWidget(self.old_results)
        self.new_results = QtWidgets.QTextEdit(Form_Matching)
        self.new_results.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.new_results.setObjectName("new_results")
        self.horizontalLayout_7.addWidget(self.new_results)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 0, 0, 1, 1)

        self.retranslateUi(Form_Matching)
        QtCore.QMetaObject.connectSlotsByName(Form_Matching)
        Form_Matching.setTabOrder(self.periodic_solution, self.lineEdit_beta_x_in)
        Form_Matching.setTabOrder(self.lineEdit_beta_x_in, self.lineEdit_beta_y_in)
        Form_Matching.setTabOrder(self.lineEdit_beta_y_in, self.lineEdit_alpha_x_in)
        Form_Matching.setTabOrder(self.lineEdit_alpha_x_in, self.lineEdit_alpha_y_in)
        Form_Matching.setTabOrder(self.lineEdit_alpha_y_in, self.lineEdit_Dx_in)
        Form_Matching.setTabOrder(self.lineEdit_Dx_in, self.lineEdit_Dxp_in)
        Form_Matching.setTabOrder(self.lineEdit_Dxp_in, self.lineEdit_beta_x_out)
        Form_Matching.setTabOrder(self.lineEdit_beta_x_out, self.lineEdit_beta_y_out)
        Form_Matching.setTabOrder(self.lineEdit_beta_y_out, self.lineEdit_alpha_x_out)
        Form_Matching.setTabOrder(self.lineEdit_alpha_x_out, self.lineEdit_alpha_y_out)
        Form_Matching.setTabOrder(self.lineEdit_alpha_y_out, self.lineEdit_Dx_out)
        Form_Matching.setTabOrder(self.lineEdit_Dx_out, self.lineEdit_Dxp_out)
        Form_Matching.setTabOrder(self.lineEdit_Dxp_out, self.lineEdit_beta_x_all)
        Form_Matching.setTabOrder(self.lineEdit_beta_x_all, self.lineEdit_beta_y_all)
        Form_Matching.setTabOrder(self.lineEdit_beta_y_all, self.lineEdit_alpha_x_all)
        Form_Matching.setTabOrder(self.lineEdit_alpha_x_all, self.lineEdit_alpha_y_all)
        Form_Matching.setTabOrder(self.lineEdit_alpha_y_all, self.lineEdit_Dx_all)
        Form_Matching.setTabOrder(self.lineEdit_Dx_all, self.lineEdit_Dxp_all)
        Form_Matching.setTabOrder(self.lineEdit_Dxp_all, self.comboBox_beta_x_in)
        Form_Matching.setTabOrder(self.comboBox_beta_x_in, self.comboBox_beta_y_in)
        Form_Matching.setTabOrder(self.comboBox_beta_y_in, self.comboBox_alpha_x_in)
        Form_Matching.setTabOrder(self.comboBox_alpha_x_in, self.comboBox_alpha_y_in)
        Form_Matching.setTabOrder(self.comboBox_alpha_y_in, self.comboBox_Dx_in)
        Form_Matching.setTabOrder(self.comboBox_Dx_in, self.comboBox_Dxp_in)
        Form_Matching.setTabOrder(self.comboBox_Dxp_in, self.comboBox_beta_x_out)
        Form_Matching.setTabOrder(self.comboBox_beta_x_out, self.comboBox_beta_y_out)
        Form_Matching.setTabOrder(self.comboBox_beta_y_out, self.comboBox_alpha_x_out)
        Form_Matching.setTabOrder(self.comboBox_alpha_x_out, self.comboBox_alpha_y_out)
        Form_Matching.setTabOrder(self.comboBox_alpha_y_out, self.comboBox_Dx_out)
        Form_Matching.setTabOrder(self.comboBox_Dx_out, self.comboBox_Dxp_out)
        Form_Matching.setTabOrder(self.comboBox_Dxp_out, self.comboBox_beta_x_all)
        Form_Matching.setTabOrder(self.comboBox_beta_x_all, self.comboBox_beta_y_all)
        Form_Matching.setTabOrder(self.comboBox_beta_y_all, self.comboBox_alpha_x_all)
        Form_Matching.setTabOrder(self.comboBox_alpha_x_all, self.comboBox_alpha_y_all)
        Form_Matching.setTabOrder(self.comboBox_alpha_y_all, self.comboBox_Dx_all)
        Form_Matching.setTabOrder(self.comboBox_Dx_all, self.comboBox_Dxp_all)
        Form_Matching.setTabOrder(self.comboBox_Dxp_all, self.btn2)
        Form_Matching.setTabOrder(self.btn2, self.btn1)
        Form_Matching.setTabOrder(self.btn1, self.old_results)
        Form_Matching.setTabOrder(self.old_results, self.new_results)

    def retranslateUi(self, Form_Matching):
        _translate = QtCore.QCoreApplication.translate
        Form_Matching.setWindowTitle(_translate("Form_Matching", "Matching parameters"))
        self.label_4.setText(_translate("Form_Matching", "Constraints"))
        self.periodic_solution.setText(_translate("Form_Matching", "Periodic solution"))
        self.label_23.setText(_translate("Form_Matching", "At lattice start"))
        self.comboBox_beta_x_in.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_beta_x_in.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_beta_x_in.setItemText(3, _translate("Form_Matching", ">"))
        self.label_7.setText(_translate("Form_Matching", "alpha_x"))
        self.label_5.setText(_translate("Form_Matching", "beta_x"))
        self.label_9.setText(_translate("Form_Matching", "Dx"))
        self.comboBox_beta_y_in.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_beta_y_in.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_beta_y_in.setItemText(3, _translate("Form_Matching", ">"))
        self.comboBox_alpha_y_in.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_alpha_y_in.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_alpha_y_in.setItemText(3, _translate("Form_Matching", ">"))
        self.label_6.setText(_translate("Form_Matching", "beta_y"))
        self.comboBox_alpha_x_in.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_alpha_x_in.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_alpha_x_in.setItemText(3, _translate("Form_Matching", ">"))
        self.label_8.setText(_translate("Form_Matching", "alpha_y"))
        self.comboBox_Dx_in.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_Dx_in.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_Dx_in.setItemText(3, _translate("Form_Matching", ">"))
        self.label_10.setText(_translate("Form_Matching", "Dxp"))
        self.comboBox_Dxp_in.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_Dxp_in.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_Dxp_in.setItemText(3, _translate("Form_Matching", ">"))
        self.label_24.setText(_translate("Form_Matching", "At lattice end"))
        self.comboBox_beta_x_out.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_beta_x_out.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_beta_x_out.setItemText(3, _translate("Form_Matching", ">"))
        self.label_13.setText(_translate("Form_Matching", "alpha_x"))
        self.comboBox_alpha_x_out.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_alpha_x_out.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_alpha_x_out.setItemText(3, _translate("Form_Matching", ">"))
        self.label_11.setText(_translate("Form_Matching", "beta_x"))
        self.label_12.setText(_translate("Form_Matching", "beta_y"))
        self.comboBox_beta_y_out.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_beta_y_out.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_beta_y_out.setItemText(3, _translate("Form_Matching", ">"))
        self.comboBox_Dx_out.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_Dx_out.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_Dx_out.setItemText(3, _translate("Form_Matching", ">"))
        self.label_15.setText(_translate("Form_Matching", "Dx"))
        self.label_14.setText(_translate("Form_Matching", "alpha_y"))
        self.comboBox_alpha_y_out.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_alpha_y_out.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_alpha_y_out.setItemText(3, _translate("Form_Matching", ">"))
        self.label_16.setText(_translate("Form_Matching", "Dxp"))
        self.comboBox_Dxp_out.setItemText(1, _translate("Form_Matching", "="))
        self.comboBox_Dxp_out.setItemText(2, _translate("Form_Matching", "<"))
        self.comboBox_Dxp_out.setItemText(3, _translate("Form_Matching", ">"))
        self.label_25.setText(_translate("Form_Matching", "Along all lattice"))
        self.comboBox_beta_x_all.setItemText(1, _translate("Form_Matching", "<"))
        self.comboBox_beta_x_all.setItemText(2, _translate("Form_Matching", ">"))
        self.label_18.setText(_translate("Form_Matching", "beta_y"))
        self.comboBox_alpha_y_all.setItemText(1, _translate("Form_Matching", "<"))
        self.comboBox_alpha_y_all.setItemText(2, _translate("Form_Matching", ">"))
        self.label_17.setText(_translate("Form_Matching", "beta_x"))
        self.label_19.setText(_translate("Form_Matching", "alpha_x"))
        self.label_20.setText(_translate("Form_Matching", "alpha_y"))
        self.comboBox_Dx_all.setItemText(1, _translate("Form_Matching", "<"))
        self.comboBox_Dx_all.setItemText(2, _translate("Form_Matching", ">"))
        self.comboBox_alpha_x_all.setItemText(1, _translate("Form_Matching", "<"))
        self.comboBox_alpha_x_all.setItemText(2, _translate("Form_Matching", ">"))
        self.comboBox_beta_y_all.setItemText(1, _translate("Form_Matching", "<"))
        self.comboBox_beta_y_all.setItemText(2, _translate("Form_Matching", ">"))
        self.label_21.setText(_translate("Form_Matching", "Dx"))
        self.label_22.setText(_translate("Form_Matching", "Dxp"))
        self.comboBox_Dxp_all.setItemText(1, _translate("Form_Matching", "<"))
        self.comboBox_Dxp_all.setItemText(2, _translate("Form_Matching", ">"))
        self.btn2.setText(_translate("Form_Matching", "Matching"))
        self.btn1.setText(_translate("Form_Matching", "Reset matching results"))
        self.label_2.setText(_translate("Form_Matching", "Matching results"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Matching = QtWidgets.QWidget()
    ui = Ui_Form_Matching()
    ui.setupUi(Form_Matching)
    Form_Matching.show()
    sys.exit(app.exec_())

