[build-system]
requires = ["setuptools>=77.0.3"]
build-backend = "setuptools.build_meta"

[project]
name = "ocelot-collab"
version = '26.06.1'
description = "Accelerator, radiation and x-ray optics simulation framework"
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.10"
license = "GPL-3.0-only"
license-files = ["LICENSE"]
authors = [
	{ name = "ocelot-collab", email = "sergey.tomin@desy.de" },
]
dependencies = [
	"numpy==2.2",
	"scipy<=1.13",
	"scikit-learn>=1.9",
	"matplotlib>=3.7,<=3.9",
	"pandas>=3.0",
	"h5py>=3.14",
	"tfs-pandas>=4.0",
	"numexpr>=2.6.1",
	"pyfftw>=0.10",
	"numba",
]

[project.urls]
Homepage = "https://github.com/ocelot-collab/ocelot"
Repository = "https://github.com/ocelot-collab/ocelot"

[project.optional-dependencies]
mpi = ["mpi4py"]
pmd = ["openpmd-api", "openpmd-viewer", "pmd-beamphysics"]
moga = ["deap"]
dev = ["invoke", "build", "Sphinx", "alabaster", "sphinxcontrib-jsmath", "pytest", "ipykernel", "ipywidgets", "nbconvert", "sympy", "imageio", "seaborn", "plotly"]

[tool.setuptools]
include-package-data = false

[tool.setuptools.packages.find]
include = ["ocelot", "ocelot.*", "demos", "demos.*"]

[tool.setuptools.package-data]
"ocelot.optics" = ["data/*.dat"]
"ocelot" = ["py.typed"]