# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'app/ui_forms/sim_matching.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1200, 750)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(10, 0, 121, 16))
        self.label.setObjectName("label")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(880, 0, 154, 16))
        self.label_3.setObjectName("label_3")
        self.btn1 = QtWidgets.QPushButton(Form)
        self.btn1.setGeometry(QtCore.QRect(993, 710, 101, 23))
        self.btn1.setObjectName("btn1")
        self.btn2 = QtWidgets.QPushButton(Form)
        self.btn2.setGeometry(QtCore.QRect(1100, 710, 80, 23))
        self.btn2.setObjectName("btn2")
        self.lattice_plot_widget = QtWidgets.QWidget(Form)
        self.lattice_plot_widget.setGeometry(QtCore.QRect(10, 20, 850, 150))
        self.lattice_plot_widget.setObjectName("lattice_plot_widget")
        self.scroll = QtWidgets.QScrollArea(Form)
        self.scroll.setGeometry(QtCore.QRect(880, 20, 300, 650))
        self.scroll.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.scroll.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.scroll.setWidgetResizable(True)
        self.scroll.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.scroll.setObjectName("scroll")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 284, 648))
        self.scrollAreaWidgetContents.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.scrollAreaWidgetContents)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 281, 80))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.widgetArea = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.widgetArea.setContentsMargins(0, 0, 0, 2)
        self.widgetArea.setSpacing(0)
        self.widgetArea.setObjectName("widgetArea")
        self.scroll.setWidget(self.scrollAreaWidgetContents)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(10, 450, 121, 16))
        self.label_2.setObjectName("label_2")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(10, 180, 81, 16))
        self.label_4.setObjectName("label_4")
        self.results = QtWidgets.QTextEdit(Form)
        self.results.setGeometry(QtCore.QRect(10, 470, 850, 200))
        self.results.setReadOnly(True)
        self.results.setObjectName("results")
        self.periodic_solution = QtWidgets.QCheckBox(Form)
        self.periodic_solution.setGeometry(QtCore.QRect(10, 220, 131, 21))
        self.periodic_solution.setObjectName("periodic_solution")
        self.gridLayoutWidget = QtWidgets.QWidget(Form)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(139, 209, 721, 251))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_9.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 4, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_14.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 3, 3, 1, 1)
        self.comboBox_alpha_x_out = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_alpha_x_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_x_out.setObjectName("comboBox_alpha_x_out")
        self.comboBox_alpha_x_out.addItem("")
        self.comboBox_alpha_x_out.setItemText(0, "")
        self.comboBox_alpha_x_out.addItem("")
        self.comboBox_alpha_x_out.addItem("")
        self.comboBox_alpha_x_out.addItem("")
        self.gridLayout.addWidget(self.comboBox_alpha_x_out, 2, 4, 1, 1)
        self.comboBox_alpha_y_out = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_alpha_y_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_y_out.setObjectName("comboBox_alpha_y_out")
        self.comboBox_alpha_y_out.addItem("")
        self.comboBox_alpha_y_out.setItemText(0, "")
        self.comboBox_alpha_y_out.addItem("")
        self.comboBox_alpha_y_out.addItem("")
        self.comboBox_alpha_y_out.addItem("")
        self.gridLayout.addWidget(self.comboBox_alpha_y_out, 3, 4, 1, 1)
        self.lineEdit_alpha_y_in = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_alpha_y_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_y_in.setObjectName("lineEdit_alpha_y_in")
        self.gridLayout.addWidget(self.lineEdit_alpha_y_in, 3, 2, 1, 1)
        self.lineEdit_Dx_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Dx_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dx_out.setObjectName("lineEdit_Dx_out")
        self.gridLayout.addWidget(self.lineEdit_Dx_out, 4, 5, 1, 1)
        self.lineEdit_Dx_all = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Dx_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dx_all.setObjectName("lineEdit_Dx_all")
        self.gridLayout.addWidget(self.lineEdit_Dx_all, 4, 8, 1, 1)
        self.lineEdit_alpha_x_in = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_alpha_x_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_x_in.setObjectName("lineEdit_alpha_x_in")
        self.gridLayout.addWidget(self.lineEdit_alpha_x_in, 2, 2, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_22.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 5, 6, 1, 1)
        self.lineEdit_beta_x_all = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_beta_x_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_x_all.setObjectName("lineEdit_beta_x_all")
        self.gridLayout.addWidget(self.lineEdit_beta_x_all, 0, 8, 1, 1)
        self.comboBox_beta_y_in = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_beta_y_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_y_in.setObjectName("comboBox_beta_y_in")
        self.comboBox_beta_y_in.addItem("")
        self.comboBox_beta_y_in.setItemText(0, "")
        self.comboBox_beta_y_in.addItem("")
        self.comboBox_beta_y_in.addItem("")
        self.comboBox_beta_y_in.addItem("")
        self.gridLayout.addWidget(self.comboBox_beta_y_in, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_8.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_10.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 5, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_12.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 1, 3, 1, 1)
        self.lineEdit_beta_y_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_beta_y_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_y_out.setObjectName("lineEdit_beta_y_out")
        self.gridLayout.addWidget(self.lineEdit_beta_y_out, 1, 5, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_13.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 2, 3, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_16.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 5, 3, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_7.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 4, 6, 1, 1)
        self.lineEdit_Dxp_in = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Dxp_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dxp_in.setObjectName("lineEdit_Dxp_in")
        self.gridLayout.addWidget(self.lineEdit_Dxp_in, 5, 2, 1, 1)
        self.lineEdit_Dxp_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Dxp_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dxp_out.setObjectName("lineEdit_Dxp_out")
        self.gridLayout.addWidget(self.lineEdit_Dxp_out, 5, 5, 1, 1)
        self.lineEdit_beta_y_all = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_beta_y_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_y_all.setObjectName("lineEdit_beta_y_all")
        self.gridLayout.addWidget(self.lineEdit_beta_y_all, 1, 8, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_18.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 6, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_20.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 3, 6, 1, 1)
        self.lineEdit_Dx_in = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Dx_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dx_in.setObjectName("lineEdit_Dx_in")
        self.gridLayout.addWidget(self.lineEdit_Dx_in, 4, 2, 1, 1)
        self.lineEdit_alpha_x_all = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_alpha_x_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_x_all.setObjectName("lineEdit_alpha_x_all")
        self.gridLayout.addWidget(self.lineEdit_alpha_x_all, 2, 8, 1, 1)
        self.comboBox_alpha_y_in = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_alpha_y_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_y_in.setObjectName("comboBox_alpha_y_in")
        self.comboBox_alpha_y_in.addItem("")
        self.comboBox_alpha_y_in.setItemText(0, "")
        self.comboBox_alpha_y_in.addItem("")
        self.comboBox_alpha_y_in.addItem("")
        self.comboBox_alpha_y_in.addItem("")
        self.gridLayout.addWidget(self.comboBox_alpha_y_in, 3, 1, 1, 1)
        self.lineEdit_beta_x_in = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_beta_x_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_x_in.setObjectName("lineEdit_beta_x_in")
        self.gridLayout.addWidget(self.lineEdit_beta_x_in, 0, 2, 1, 1)
        self.comboBox_alpha_x_in = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_alpha_x_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_x_in.setObjectName("comboBox_alpha_x_in")
        self.comboBox_alpha_x_in.addItem("")
        self.comboBox_alpha_x_in.setItemText(0, "")
        self.comboBox_alpha_x_in.addItem("")
        self.comboBox_alpha_x_in.addItem("")
        self.comboBox_alpha_x_in.addItem("")
        self.gridLayout.addWidget(self.comboBox_alpha_x_in, 2, 1, 1, 1)
        self.comboBox_Dxp_in = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Dxp_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dxp_in.setObjectName("comboBox_Dxp_in")
        self.comboBox_Dxp_in.addItem("")
        self.comboBox_Dxp_in.setItemText(0, "")
        self.comboBox_Dxp_in.addItem("")
        self.comboBox_Dxp_in.addItem("")
        self.comboBox_Dxp_in.addItem("")
        self.gridLayout.addWidget(self.comboBox_Dxp_in, 5, 1, 1, 1)
        self.lineEdit_alpha_y_all = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_alpha_y_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_y_all.setObjectName("lineEdit_alpha_y_all")
        self.gridLayout.addWidget(self.lineEdit_alpha_y_all, 3, 8, 1, 1)
        self.comboBox_Dxp_all = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Dxp_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dxp_all.setObjectName("comboBox_Dxp_all")
        self.comboBox_Dxp_all.addItem("")
        self.comboBox_Dxp_all.setItemText(0, "")
        self.comboBox_Dxp_all.addItem("")
        self.comboBox_Dxp_all.addItem("")
        self.gridLayout.addWidget(self.comboBox_Dxp_all, 5, 7, 1, 1)
        self.comboBox_alpha_y_all = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_alpha_y_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_y_all.setObjectName("comboBox_alpha_y_all")
        self.comboBox_alpha_y_all.addItem("")
        self.comboBox_alpha_y_all.setItemText(0, "")
        self.comboBox_alpha_y_all.addItem("")
        self.comboBox_alpha_y_all.addItem("")
        self.gridLayout.addWidget(self.comboBox_alpha_y_all, 3, 7, 1, 1)
        self.lineEdit_alpha_y_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_alpha_y_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_y_out.setObjectName("lineEdit_alpha_y_out")
        self.gridLayout.addWidget(self.lineEdit_alpha_y_out, 3, 5, 1, 1)
        self.comboBox_beta_x_in = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_beta_x_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_x_in.setObjectName("comboBox_beta_x_in")
        self.comboBox_beta_x_in.addItem("")
        self.comboBox_beta_x_in.setItemText(0, "")
        self.comboBox_beta_x_in.addItem("")
        self.comboBox_beta_x_in.addItem("")
        self.comboBox_beta_x_in.addItem("")
        self.gridLayout.addWidget(self.comboBox_beta_x_in, 0, 1, 1, 1)
        self.comboBox_Dx_all = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Dx_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dx_all.setObjectName("comboBox_Dx_all")
        self.comboBox_Dx_all.addItem("")
        self.comboBox_Dx_all.setItemText(0, "")
        self.comboBox_Dx_all.addItem("")
        self.comboBox_Dx_all.addItem("")
        self.gridLayout.addWidget(self.comboBox_Dx_all, 4, 7, 1, 1)
        self.lineEdit_alpha_x_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_alpha_x_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_alpha_x_out.setObjectName("lineEdit_alpha_x_out")
        self.gridLayout.addWidget(self.lineEdit_alpha_x_out, 2, 5, 1, 1)
        self.comboBox_beta_y_out = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_beta_y_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_y_out.setObjectName("comboBox_beta_y_out")
        self.comboBox_beta_y_out.addItem("")
        self.comboBox_beta_y_out.setItemText(0, "")
        self.comboBox_beta_y_out.addItem("")
        self.comboBox_beta_y_out.addItem("")
        self.comboBox_beta_y_out.addItem("")
        self.gridLayout.addWidget(self.comboBox_beta_y_out, 1, 4, 1, 1)
        self.comboBox_Dx_in = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Dx_in.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dx_in.setObjectName("comboBox_Dx_in")
        self.comboBox_Dx_in.addItem("")
        self.comboBox_Dx_in.setItemText(0, "")
        self.comboBox_Dx_in.addItem("")
        self.comboBox_Dx_in.addItem("")
        self.comboBox_Dx_in.addItem("")
        self.gridLayout.addWidget(self.comboBox_Dx_in, 4, 1, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_15.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 4, 3, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_6.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 1, 0, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_17.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 6, 1, 1)
        self.lineEdit_beta_x_out = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_beta_x_out.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_x_out.setObjectName("lineEdit_beta_x_out")
        self.gridLayout.addWidget(self.lineEdit_beta_x_out, 0, 5, 1, 1)
        self.comboBox_beta_x_all = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_beta_x_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_x_all.setObjectName("comboBox_beta_x_all")
        self.comboBox_beta_x_all.addItem("")
        self.comboBox_beta_x_all.setItemText(0, "")
        self.comboBox_beta_x_all.addItem("")
        self.comboBox_beta_x_all.addItem("")
        self.gridLayout.addWidget(self.comboBox_beta_x_all, 0, 7, 1, 1)
        self.comboBox_beta_y_all = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_beta_y_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_y_all.setObjectName("comboBox_beta_y_all")
        self.comboBox_beta_y_all.addItem("")
        self.comboBox_beta_y_all.setItemText(0, "")
        self.comboBox_beta_y_all.addItem("")
        self.comboBox_beta_y_all.addItem("")
        self.gridLayout.addWidget(self.comboBox_beta_y_all, 1, 7, 1, 1)
        self.comboBox_Dx_out = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Dx_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dx_out.setObjectName("comboBox_Dx_out")
        self.comboBox_Dx_out.addItem("")
        self.comboBox_Dx_out.setItemText(0, "")
        self.comboBox_Dx_out.addItem("")
        self.comboBox_Dx_out.addItem("")
        self.comboBox_Dx_out.addItem("")
        self.gridLayout.addWidget(self.comboBox_Dx_out, 4, 4, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout.addWidget(self.label_19, 2, 6, 1, 1)
        self.comboBox_alpha_x_all = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_alpha_x_all.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_alpha_x_all.setObjectName("comboBox_alpha_x_all")
        self.comboBox_alpha_x_all.addItem("")
        self.comboBox_alpha_x_all.setItemText(0, "")
        self.comboBox_alpha_x_all.addItem("")
        self.comboBox_alpha_x_all.addItem("")
        self.gridLayout.addWidget(self.comboBox_alpha_x_all, 2, 7, 1, 1)
        self.comboBox_Dxp_out = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_Dxp_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_Dxp_out.setObjectName("comboBox_Dxp_out")
        self.comboBox_Dxp_out.addItem("")
        self.comboBox_Dxp_out.setItemText(0, "")
        self.comboBox_Dxp_out.addItem("")
        self.comboBox_Dxp_out.addItem("")
        self.comboBox_Dxp_out.addItem("")
        self.gridLayout.addWidget(self.comboBox_Dxp_out, 5, 4, 1, 1)
        self.comboBox_beta_x_out = QtWidgets.QComboBox(self.gridLayoutWidget)
        self.comboBox_beta_x_out.setMaximumSize(QtCore.QSize(45, 16777215))
        self.comboBox_beta_x_out.setObjectName("comboBox_beta_x_out")
        self.comboBox_beta_x_out.addItem("")
        self.comboBox_beta_x_out.setItemText(0, "")
        self.comboBox_beta_x_out.addItem("")
        self.comboBox_beta_x_out.addItem("")
        self.comboBox_beta_x_out.addItem("")
        self.gridLayout.addWidget(self.comboBox_beta_x_out, 0, 4, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.gridLayoutWidget)
        self.label_11.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 0, 3, 1, 1)
        self.lineEdit_Dxp_all = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_Dxp_all.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_Dxp_all.setObjectName("lineEdit_Dxp_all")
        self.gridLayout.addWidget(self.lineEdit_Dxp_all, 5, 8, 1, 1)
        self.lineEdit_beta_y_in = QtWidgets.QLineEdit(self.gridLayoutWidget)
        self.lineEdit_beta_y_in.setMaximumSize(QtCore.QSize(75, 16777215))
        self.lineEdit_beta_y_in.setObjectName("lineEdit_beta_y_in")
        self.gridLayout.addWidget(self.lineEdit_beta_y_in, 1, 2, 1, 1)
        self.horizontalLayoutWidget = QtWidgets.QWidget(Form)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(159, 190, 701, 20))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_23 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout.addWidget(self.label_23)
        self.label_24 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout.addWidget(self.label_24)
        self.label_25 = QtWidgets.QLabel(self.horizontalLayoutWidget)
        self.label_25.setMaximumSize(QtCore.QSize(16777215, 15))
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout.addWidget(self.label_25)
        self.label.raise_()
        self.label_3.raise_()
        self.btn1.raise_()
        self.btn2.raise_()
        self.lattice_plot_widget.raise_()
        self.scroll.raise_()
        self.label_2.raise_()
        self.label_4.raise_()
        self.results.raise_()
        self.periodic_solution.raise_()
        self.gridLayoutWidget.raise_()
        self.horizontalLayoutWidget.raise_()
        self.label_25.raise_()

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Lattice"))
        self.label_3.setText(_translate("Form", "Matching variables"))
        self.btn1.setText(_translate("Form", "Apply results"))
        self.btn2.setText(_translate("Form", "Matching"))
        self.label_2.setText(_translate("Form", "Matching results"))
        self.label_4.setText(_translate("Form", "Constraints"))
        self.periodic_solution.setText(_translate("Form", "Periodic solution"))
        self.label_9.setText(_translate("Form", "Dx"))
        self.label_14.setText(_translate("Form", "alpha_y"))
        self.comboBox_alpha_x_out.setItemText(1, _translate("Form", "="))
        self.comboBox_alpha_x_out.setItemText(2, _translate("Form", "<"))
        self.comboBox_alpha_x_out.setItemText(3, _translate("Form", ">"))
        self.comboBox_alpha_y_out.setItemText(1, _translate("Form", "="))
        self.comboBox_alpha_y_out.setItemText(2, _translate("Form", "<"))
        self.comboBox_alpha_y_out.setItemText(3, _translate("Form", ">"))
        self.label_22.setText(_translate("Form", "Dxp"))
        self.comboBox_beta_y_in.setItemText(1, _translate("Form", "="))
        self.comboBox_beta_y_in.setItemText(2, _translate("Form", "<"))
        self.comboBox_beta_y_in.setItemText(3, _translate("Form", ">"))
        self.label_8.setText(_translate("Form", "alpha_y"))
        self.label_10.setText(_translate("Form", "Dxp"))
        self.label_12.setText(_translate("Form", "beta_y"))
        self.label_13.setText(_translate("Form", "alpha_x"))
        self.label_16.setText(_translate("Form", "Dxp"))
        self.label_7.setText(_translate("Form", "alpha_x"))
        self.label_21.setText(_translate("Form", "Dx"))
        self.label_18.setText(_translate("Form", "beta_y"))
        self.label_20.setText(_translate("Form", "alpha_y"))
        self.comboBox_alpha_y_in.setItemText(1, _translate("Form", "="))
        self.comboBox_alpha_y_in.setItemText(2, _translate("Form", "<"))
        self.comboBox_alpha_y_in.setItemText(3, _translate("Form", ">"))
        self.comboBox_alpha_x_in.setItemText(1, _translate("Form", "="))
        self.comboBox_alpha_x_in.setItemText(2, _translate("Form", "<"))
        self.comboBox_alpha_x_in.setItemText(3, _translate("Form", ">"))
        self.comboBox_Dxp_in.setItemText(1, _translate("Form", "="))
        self.comboBox_Dxp_in.setItemText(2, _translate("Form", "<"))
        self.comboBox_Dxp_in.setItemText(3, _translate("Form", ">"))
        self.comboBox_Dxp_all.setItemText(1, _translate("Form", "<"))
        self.comboBox_Dxp_all.setItemText(2, _translate("Form", ">"))
        self.comboBox_alpha_y_all.setItemText(1, _translate("Form", "<"))
        self.comboBox_alpha_y_all.setItemText(2, _translate("Form", ">"))
        self.comboBox_beta_x_in.setItemText(1, _translate("Form", "="))
        self.comboBox_beta_x_in.setItemText(2, _translate("Form", "<"))
        self.comboBox_beta_x_in.setItemText(3, _translate("Form", ">"))
        self.comboBox_Dx_all.setItemText(1, _translate("Form", "<"))
        self.comboBox_Dx_all.setItemText(2, _translate("Form", ">"))
        self.comboBox_beta_y_out.setItemText(1, _translate("Form", "="))
        self.comboBox_beta_y_out.setItemText(2, _translate("Form", "<"))
        self.comboBox_beta_y_out.setItemText(3, _translate("Form", ">"))
        self.comboBox_Dx_in.setItemText(1, _translate("Form", "="))
        self.comboBox_Dx_in.setItemText(2, _translate("Form", "<"))
        self.comboBox_Dx_in.setItemText(3, _translate("Form", ">"))
        self.label_15.setText(_translate("Form", "Dx"))
        self.label_5.setText(_translate("Form", "beta_x"))
        self.label_6.setText(_translate("Form", "beta_y"))
        self.label_17.setText(_translate("Form", "beta_x"))
        self.comboBox_beta_x_all.setItemText(1, _translate("Form", "<"))
        self.comboBox_beta_x_all.setItemText(2, _translate("Form", ">"))
        self.comboBox_beta_y_all.setItemText(1, _translate("Form", "<"))
        self.comboBox_beta_y_all.setItemText(2, _translate("Form", ">"))
        self.comboBox_Dx_out.setItemText(1, _translate("Form", "="))
        self.comboBox_Dx_out.setItemText(2, _translate("Form", "<"))
        self.comboBox_Dx_out.setItemText(3, _translate("Form", ">"))
        self.label_19.setText(_translate("Form", "alpha_x"))
        self.comboBox_alpha_x_all.setItemText(1, _translate("Form", "<"))
        self.comboBox_alpha_x_all.setItemText(2, _translate("Form", ">"))
        self.comboBox_Dxp_out.setItemText(1, _translate("Form", "="))
        self.comboBox_Dxp_out.setItemText(2, _translate("Form", "<"))
        self.comboBox_Dxp_out.setItemText(3, _translate("Form", ">"))
        self.comboBox_beta_x_out.setItemText(1, _translate("Form", "="))
        self.comboBox_beta_x_out.setItemText(2, _translate("Form", "<"))
        self.comboBox_beta_x_out.setItemText(3, _translate("Form", ">"))
        self.label_11.setText(_translate("Form", "beta_x"))
        self.label_23.setText(_translate("Form", "At lattice start"))
        self.label_24.setText(_translate("Form", "At lattice end"))
        self.label_25.setText(_translate("Form", "Along all lattice"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

