# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'UIOcelotInterface_gen.ui'
#
# Created: Mon Jun 19 00:18:08 2017
#      by: PyQt4 UI code generator 4.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName(_fromUtf8("Form"))
        Form.resize(1100, 1022)
        Form.setMinimumSize(QtCore.QSize(400, 0))
        Form.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        #Form.setStyleSheet(_fromUtf8("background-color: white"))
        self.gridLayout = QtGui.QGridLayout(Form)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.tabWidget = QtGui.QTabWidget(Form)
        self.tabWidget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 35))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_9 = QtGui.QGridLayout(self.tab)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.widget = ResetpanelBoxWindow(self.tab)
        self.widget.setEnabled(True)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(600, 0))
        self.widget.setObjectName(_fromUtf8("widget"))
        self.gridLayout_9.addWidget(self.widget, 0, 0, 2, 1)
        self.widget_2 = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.gridLayout_9.addWidget(self.widget_2, 0, 1, 1, 1)
        self.widget_3 = QtGui.QWidget(self.tab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.gridLayout_9.addWidget(self.widget_3, 1, 1, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.pb_start_scan = QtGui.QPushButton(self.tab)
        self.pb_start_scan.setMinimumSize(QtCore.QSize(150, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_start_scan.setFont(font)
        self.pb_start_scan.setStyleSheet(_fromUtf8("color: rgb(85, 255, 127);"))
        self.pb_start_scan.setObjectName(_fromUtf8("pb_start_scan"))
        self.horizontalLayout_2.addWidget(self.pb_start_scan)
        self.pb_logbook = QtGui.QPushButton(self.tab)
        self.pb_logbook.setMinimumSize(QtCore.QSize(0, 60))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(True)
        font.setWeight(75)
        self.pb_logbook.setFont(font)
        self.pb_logbook.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.pb_logbook.setObjectName(_fromUtf8("pb_logbook"))
        self.horizontalLayout_2.addWidget(self.pb_logbook)
        self.frame = QtGui.QFrame(self.tab)
        self.frame.setMinimumSize(QtCore.QSize(0, 60))
        self.frame.setMaximumSize(QtCore.QSize(16777215, 60))
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Plain)
        self.frame.setLineWidth(0)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame)
        self.gridLayout_2.setSpacing(5)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.pb_help = QtGui.QPushButton(self.frame)
        self.pb_help.setMinimumSize(QtCore.QSize(0, 20))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pb_help.setFont(font)
        self.pb_help.setObjectName(_fromUtf8("pb_help"))
        self.gridLayout_2.addWidget(self.pb_help, 5, 0, 1, 1)
        self.pushButton_3 = QtGui.QPushButton(self.frame)
        self.pushButton_3.setEnabled(False)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 20))
        self.pushButton_3.setSizeIncrement(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_3.setFont(font)
        self.pushButton_3.setObjectName(_fromUtf8("pushButton_3"))
        self.gridLayout_2.addWidget(self.pushButton_3, 1, 0, 1, 1)
        self.horizontalLayout_2.addWidget(self.frame)
        self.gridLayout_9.addLayout(self.horizontalLayout_2, 2, 0, 1, 2)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab2 = QtGui.QWidget()
        self.tab2.setObjectName(_fromUtf8("tab2"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab2)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.label_3 = QtGui.QLabel(self.tab2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_3.sizePolicy().hasHeightForWidth())
        self.label_3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_3.setFont(font)
        self.label_3.setMargin(5)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.verticalLayout_12.addWidget(self.label_3)
        self.groupBox = QtGui.QGroupBox(self.tab2)
        self.groupBox.setEnabled(True)
        self.groupBox.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_5 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.label_2 = QtGui.QLabel(self.groupBox)
        self.label_2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_2.setFont(font)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.verticalLayout_6.addWidget(self.label_2)
        self.label_6 = QtGui.QLabel(self.groupBox)
        self.label_6.setEnabled(True)
        self.label_6.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_6.setFont(font)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.verticalLayout_6.addWidget(self.label_6)
        self.label_30 = QtGui.QLabel(self.groupBox)
        self.label_30.setEnabled(True)
        self.label_30.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_30.setFont(font)
        self.label_30.setObjectName(_fromUtf8("label_30"))
        self.verticalLayout_6.addWidget(self.label_30)
        self.horizontalLayout.addLayout(self.verticalLayout_6)
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.sb_tdelay = QtGui.QDoubleSpinBox(self.groupBox)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_tdelay.sizePolicy().hasHeightForWidth())
        self.sb_tdelay.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_tdelay.setFont(font)
        self.sb_tdelay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_tdelay.setMinimum(0.0)
        self.sb_tdelay.setMaximum(99.99)
        self.sb_tdelay.setSingleStep(0.1)
        self.sb_tdelay.setProperty("value", 0.0)
        self.sb_tdelay.setObjectName(_fromUtf8("sb_tdelay"))
        self.verticalLayout_7.addWidget(self.sb_tdelay)
        self.sb_ddelay = QtGui.QDoubleSpinBox(self.groupBox)
        self.sb_ddelay.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_ddelay.setFont(font)
        self.sb_ddelay.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_ddelay.setMinimum(0.0)
        self.sb_ddelay.setSingleStep(0.05)
        self.sb_ddelay.setProperty("value", 0.0)
        self.sb_ddelay.setObjectName(_fromUtf8("sb_ddelay"))
        self.verticalLayout_7.addWidget(self.sb_ddelay)
        self.sb_nreadings = QtGui.QSpinBox(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_nreadings.setFont(font)
        self.sb_nreadings.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_nreadings.setMinimum(1)
        self.sb_nreadings.setProperty("value", 1)
        self.sb_nreadings.setObjectName(_fromUtf8("sb_nreadings"))
        self.verticalLayout_7.addWidget(self.sb_nreadings)
        self.horizontalLayout.addLayout(self.verticalLayout_7)
        self.gridLayout_5.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.label_7 = QtGui.QLabel(self.groupBox)
        self.label_7.setMaximumSize(QtCore.QSize(16777215, 30))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_5.addWidget(self.label_7, 1, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox)
        self.groupBox_2 = QtGui.QGroupBox(self.tab2)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setMaximumSize(QtCore.QSize(16777215, 250))
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_3 = QtGui.QGridLayout()
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.verticalLayout_3 = QtGui.QVBoxLayout()
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.label_9 = QtGui.QLabel(self.groupBox_2)
        self.label_9.setEnabled(False)
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.verticalLayout_3.addWidget(self.label_9)
        self.label_8 = QtGui.QLabel(self.groupBox_2)
        self.label_8.setEnabled(False)
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_8.setFont(font)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.verticalLayout_3.addWidget(self.label_8)
        self.label_10 = QtGui.QLabel(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_10.setFont(font)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.verticalLayout_3.addWidget(self.label_10)
        self.gridLayout_3.addLayout(self.verticalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.pb_hyper_file = QtGui.QPushButton(self.groupBox_2)
        self.pb_hyper_file.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_hyper_file.sizePolicy().hasHeightForWidth())
        self.pb_hyper_file.setSizePolicy(sizePolicy)
        self.pb_hyper_file.setMaximumSize(QtCore.QSize(16777215, 43))
        self.pb_hyper_file.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.pb_hyper_file.setFont(font)
        self.pb_hyper_file.setObjectName(_fromUtf8("pb_hyper_file"))
        self.verticalLayout_2.addWidget(self.pb_hyper_file)
        self.lineEdit_4 = QtGui.QLineEdit(self.groupBox_2)
        self.lineEdit_4.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_4.setFont(font)
        self.lineEdit_4.setObjectName(_fromUtf8("lineEdit_4"))
        self.verticalLayout_2.addWidget(self.lineEdit_4)
        self.sb_seed_iter = QtGui.QSpinBox(self.groupBox_2)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_seed_iter.setFont(font)
        self.sb_seed_iter.setMinimum(1)
        self.sb_seed_iter.setProperty("value", 5)
        self.sb_seed_iter.setObjectName(_fromUtf8("sb_seed_iter"))
        self.verticalLayout_2.addWidget(self.sb_seed_iter)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.cb_use_live_seed = QtGui.QCheckBox(self.groupBox_2)
        self.cb_use_live_seed.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_use_live_seed.setFont(font)
        self.cb_use_live_seed.setObjectName(_fromUtf8("cb_use_live_seed"))
        self.gridLayout_3.addWidget(self.cb_use_live_seed, 1, 0, 1, 2)
        self.gridLayout_7.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_2)
        self.groupBox_5 = QtGui.QGroupBox(self.tab2)
        self.groupBox_5.setEnabled(True)
        self.groupBox_5.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_5.setObjectName(_fromUtf8("groupBox_5"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox_5)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        self.pb_save_as = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_save_as.sizePolicy().hasHeightForWidth())
        self.pb_save_as.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_save_as.setFont(font)
        self.pb_save_as.setObjectName(_fromUtf8("pb_save_as"))
        self.horizontalLayout_7.addWidget(self.pb_save_as)
        self.pb_load = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_load.sizePolicy().hasHeightForWidth())
        self.pb_load.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_load.setFont(font)
        self.pb_load.setObjectName(_fromUtf8("pb_load"))
        self.horizontalLayout_7.addWidget(self.pb_load)
        self.pb_rewrite = QtGui.QPushButton(self.groupBox_5)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_rewrite.sizePolicy().hasHeightForWidth())
        self.pb_rewrite.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.pb_rewrite.setFont(font)
        self.pb_rewrite.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pb_rewrite.setObjectName(_fromUtf8("pb_rewrite"))
        self.horizontalLayout_7.addWidget(self.pb_rewrite)
        self.verticalLayout_11.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_4.addLayout(self.verticalLayout_11)
        self.gridLayout_8.addLayout(self.horizontalLayout_4, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_5)
        self.groupBox_4 = QtGui.QGroupBox(self.tab2)
        self.groupBox_4.setEnabled(False)
        self.groupBox_4.setObjectName(_fromUtf8("groupBox_4"))
        self.gridLayout_6 = QtGui.QGridLayout(self.groupBox_4)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.checkBox_2 = QtGui.QCheckBox(self.groupBox_4)
        self.checkBox_2.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.checkBox_2.setFont(font)
        self.checkBox_2.setObjectName(_fromUtf8("checkBox_2"))
        self.verticalLayout_8.addWidget(self.checkBox_2)
        self.label_11 = QtGui.QLabel(self.groupBox_4)
        self.label_11.setEnabled(False)
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_11.setFont(font)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.verticalLayout_8.addWidget(self.label_11)
        self.horizontalLayout_3.addLayout(self.verticalLayout_8)
        self.verticalLayout_9 = QtGui.QVBoxLayout()
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.lineEdit_7 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_7.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_7.setFont(font)
        self.lineEdit_7.setObjectName(_fromUtf8("lineEdit_7"))
        self.verticalLayout_9.addWidget(self.lineEdit_7)
        self.lineEdit_8 = QtGui.QLineEdit(self.groupBox_4)
        self.lineEdit_8.setEnabled(False)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.lineEdit_8.setFont(font)
        self.lineEdit_8.setObjectName(_fromUtf8("lineEdit_8"))
        self.verticalLayout_9.addWidget(self.lineEdit_8)
        self.horizontalLayout_3.addLayout(self.verticalLayout_9)
        self.gridLayout_6.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.verticalLayout_12.addWidget(self.groupBox_4)
        self.label_4 = QtGui.QLabel(self.tab2)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(True)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setText(_fromUtf8(""))
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setMargin(5)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout_12.addWidget(self.label_4)
        self.pushButton_4 = QtGui.QPushButton(self.tab2)
        self.pushButton_4.setEnabled(False)
        self.pushButton_4.setMinimumSize(QtCore.QSize(0, 50))
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_4.setFont(font)
        self.pushButton_4.setObjectName(_fromUtf8("pushButton_4"))
        self.verticalLayout_12.addWidget(self.pushButton_4)
        self.tabWidget.addTab(self.tab2, _fromUtf8(""))
        self.tab3 = QtGui.QWidget()
        self.tab3.setObjectName(_fromUtf8("tab3"))
        self.verticalLayout_10 = QtGui.QVBoxLayout(self.tab3)
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.verticalLayout_19 = QtGui.QVBoxLayout()
        self.verticalLayout_19.setObjectName(_fromUtf8("verticalLayout_19"))
        self.label_18 = QtGui.QLabel(self.tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_18.sizePolicy().hasHeightForWidth())
        self.label_18.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(30)
        self.label_18.setFont(font)
        self.label_18.setMargin(5)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.verticalLayout_19.addWidget(self.label_18)
        self.verticalLayout_10.addLayout(self.verticalLayout_19)
        self.groupBox_7 = QtGui.QGroupBox(self.tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_7.sizePolicy().hasHeightForWidth())
        self.groupBox_7.setSizePolicy(sizePolicy)
        self.groupBox_7.setMinimumSize(QtCore.QSize(0, 0))
        self.groupBox_7.setMaximumSize(QtCore.QSize(16777215, 350))
        self.groupBox_7.setObjectName(_fromUtf8("groupBox_7"))
        self.gridLayout_11 = QtGui.QGridLayout(self.groupBox_7)
        self.gridLayout_11.setObjectName(_fromUtf8("gridLayout_11"))
        self.pb_edit_obj_func = QtGui.QPushButton(self.groupBox_7)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pb_edit_obj_func.sizePolicy().hasHeightForWidth())
        self.pb_edit_obj_func.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.pb_edit_obj_func.setFont(font)
        self.pb_edit_obj_func.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.pb_edit_obj_func.setObjectName(_fromUtf8("pb_edit_obj_func"))
        self.gridLayout_11.addWidget(self.pb_edit_obj_func, 8, 0, 1, 2)
        self.cb_use_predef = QtGui.QCheckBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.cb_use_predef.setFont(font)
        self.cb_use_predef.setObjectName(_fromUtf8("cb_use_predef"))
        self.gridLayout_11.addWidget(self.cb_use_predef, 7, 0, 1, 1)
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.le_a = QtGui.QLineEdit(self.groupBox_7)
        self.le_a.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_a.setFont(font)
        self.le_a.setText(_fromUtf8(""))
        self.le_a.setObjectName(_fromUtf8("le_a"))
        self.verticalLayout_16.addWidget(self.le_a)
        self.le_b = QtGui.QLineEdit(self.groupBox_7)
        self.le_b.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_b.setFont(font)
        self.le_b.setObjectName(_fromUtf8("le_b"))
        self.verticalLayout_16.addWidget(self.le_b)
        self.le_c = QtGui.QLineEdit(self.groupBox_7)
        self.le_c.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_c.setFont(font)
        self.le_c.setObjectName(_fromUtf8("le_c"))
        self.verticalLayout_16.addWidget(self.le_c)
        self.le_d = QtGui.QLineEdit(self.groupBox_7)
        self.le_d.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_d.setFont(font)
        self.le_d.setObjectName(_fromUtf8("le_d"))
        self.verticalLayout_16.addWidget(self.le_d)
        self.le_e = QtGui.QLineEdit(self.groupBox_7)
        self.le_e.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_e.setFont(font)
        self.le_e.setObjectName(_fromUtf8("le_e"))
        self.verticalLayout_16.addWidget(self.le_e)
        self.le_obf = QtGui.QLineEdit(self.groupBox_7)
        self.le_obf.setEnabled(True)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        font.setWeight(50)
        self.le_obf.setFont(font)
        self.le_obf.setObjectName(_fromUtf8("le_obf"))
        self.verticalLayout_16.addWidget(self.le_obf)
        self.sb_max_pen = QtGui.QSpinBox(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_max_pen.setFont(font)
        self.sb_max_pen.setMinimum(-1000)
        self.sb_max_pen.setMaximum(1000)
        self.sb_max_pen.setProperty("value", 100)
        self.sb_max_pen.setObjectName(_fromUtf8("sb_max_pen"))
        self.verticalLayout_16.addWidget(self.sb_max_pen)
        self.gridLayout_11.addLayout(self.verticalLayout_16, 0, 1, 1, 1)
        self.verticalLayout_15 = QtGui.QVBoxLayout()
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.label_16 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_16.setFont(font)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.verticalLayout_15.addWidget(self.label_16)
        self.label_19 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_19.setFont(font)
        self.label_19.setObjectName(_fromUtf8("label_19"))
        self.verticalLayout_15.addWidget(self.label_19)
        self.label_20 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_20.setFont(font)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.verticalLayout_15.addWidget(self.label_20)
        self.label_28 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_28.setFont(font)
        self.label_28.setObjectName(_fromUtf8("label_28"))
        self.verticalLayout_15.addWidget(self.label_28)
        self.label_29 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_29.setFont(font)
        self.label_29.setObjectName(_fromUtf8("label_29"))
        self.verticalLayout_15.addWidget(self.label_29)
        self.label_21 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_21.setFont(font)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.verticalLayout_15.addWidget(self.label_21)
        self.label_26 = QtGui.QLabel(self.groupBox_7)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_26.setFont(font)
        self.label_26.setObjectName(_fromUtf8("label_26"))
        self.verticalLayout_15.addWidget(self.label_26)
        self.gridLayout_11.addLayout(self.verticalLayout_15, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_7)
        self.groupBox_6 = QtGui.QGroupBox(self.tab3)
        self.groupBox_6.setEnabled(True)
        self.groupBox_6.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBox_6.setObjectName(_fromUtf8("groupBox_6"))
        self.gridLayout_10 = QtGui.QGridLayout(self.groupBox_6)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_13 = QtGui.QLabel(self.groupBox_6)
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_13.setFont(font)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.verticalLayout_13.addWidget(self.label_13)
        self.label_14 = QtGui.QLabel(self.groupBox_6)
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_14.setFont(font)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.verticalLayout_13.addWidget(self.label_14)
        self.label_15 = QtGui.QLabel(self.groupBox_6)
        self.label_15.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_15.setFont(font)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.verticalLayout_13.addWidget(self.label_15)
        self.horizontalLayout_5.addLayout(self.verticalLayout_13)
        self.verticalLayout_14 = QtGui.QVBoxLayout()
        self.verticalLayout_14.setObjectName(_fromUtf8("verticalLayout_14"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        self.le_alarm = QtGui.QLineEdit(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.le_alarm.setFont(font)
        self.le_alarm.setObjectName(_fromUtf8("le_alarm"))
        self.horizontalLayout_9.addWidget(self.le_alarm)
        self.label_12 = QtGui.QLabel(self.groupBox_6)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_9.addWidget(self.label_12)
        self.label_alarm = QtGui.QLabel(self.groupBox_6)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_alarm.setFont(font)
        self.label_alarm.setObjectName(_fromUtf8("label_alarm"))
        self.horizontalLayout_9.addWidget(self.label_alarm)
        self.verticalLayout_14.addLayout(self.horizontalLayout_9)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.label_17 = QtGui.QLabel(self.groupBox_6)
        self.label_17.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_17.setFont(font)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.horizontalLayout_6.addWidget(self.label_17)
        self.sb_alarm_min = QtGui.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_alarm_min.sizePolicy().hasHeightForWidth())
        self.sb_alarm_min.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_alarm_min.setFont(font)
        self.sb_alarm_min.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alarm_min.setMinimum(-100.0)
        self.sb_alarm_min.setMaximum(100.99)
        self.sb_alarm_min.setSingleStep(0.1)
        self.sb_alarm_min.setProperty("value", 0.0)
        self.sb_alarm_min.setObjectName(_fromUtf8("sb_alarm_min"))
        self.horizontalLayout_6.addWidget(self.sb_alarm_min)
        self.label_22 = QtGui.QLabel(self.groupBox_6)
        self.label_22.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_22.setFont(font)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.horizontalLayout_6.addWidget(self.label_22)
        self.sb_alarm_max = QtGui.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_alarm_max.sizePolicy().hasHeightForWidth())
        self.sb_alarm_max.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_alarm_max.setFont(font)
        self.sb_alarm_max.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alarm_max.setMinimum(-100.0)
        self.sb_alarm_max.setMaximum(100.99)
        self.sb_alarm_max.setSingleStep(0.1)
        self.sb_alarm_max.setObjectName(_fromUtf8("sb_alarm_max"))
        self.horizontalLayout_6.addWidget(self.sb_alarm_max)
        self.verticalLayout_14.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.sb_alarm_timeout = QtGui.QDoubleSpinBox(self.groupBox_6)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sb_alarm_timeout.sizePolicy().hasHeightForWidth())
        self.sb_alarm_timeout.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.sb_alarm_timeout.setFont(font)
        self.sb_alarm_timeout.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_alarm_timeout.setMinimum(0.0)
        self.sb_alarm_timeout.setMaximum(100.0)
        self.sb_alarm_timeout.setSingleStep(0.1)
        self.sb_alarm_timeout.setProperty("value", 2.0)
        self.sb_alarm_timeout.setObjectName(_fromUtf8("sb_alarm_timeout"))
        self.horizontalLayout_10.addWidget(self.sb_alarm_timeout)
        self.label_24 = QtGui.QLabel(self.groupBox_6)
        self.label_24.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_24.setFont(font)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.horizontalLayout_10.addWidget(self.label_24)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem)
        self.verticalLayout_14.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_5.addLayout(self.verticalLayout_14)
        self.gridLayout_10.addLayout(self.horizontalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_10.addWidget(self.groupBox_6)
        self.groupBox_8 = QtGui.QGroupBox(self.tab3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_8.sizePolicy().hasHeightForWidth())
        self.groupBox_8.setSizePolicy(sizePolicy)
        self.groupBox_8.setObjectName(_fromUtf8("groupBox_8"))
        self.verticalLayout_20 = QtGui.QVBoxLayout(self.groupBox_8)
        self.verticalLayout_20.setObjectName(_fromUtf8("verticalLayout_20"))
        self.gridLayout_12 = QtGui.QGridLayout()
        self.gridLayout_12.setObjectName(_fromUtf8("gridLayout_12"))
        self.sb_num_iter = QtGui.QSpinBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_num_iter.setFont(font)
        self.sb_num_iter.setMaximum(1000)
        self.sb_num_iter.setProperty("value", 50)
        self.sb_num_iter.setObjectName(_fromUtf8("sb_num_iter"))
        self.gridLayout_12.addWidget(self.sb_num_iter, 4, 1, 1, 1)
        self.label_27 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_27.setFont(font)
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.gridLayout_12.addWidget(self.label_27, 2, 0, 1, 1)
        self.label_25 = QtGui.QLabel(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_25.setFont(font)
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.gridLayout_12.addWidget(self.label_25, 4, 0, 1, 1)
        self.cb_select_alg = QtGui.QComboBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_select_alg.setFont(font)
        self.cb_select_alg.setObjectName(_fromUtf8("cb_select_alg"))
        self.gridLayout_12.addWidget(self.cb_select_alg, 2, 1, 1, 1)
        self.verticalLayout_20.addLayout(self.gridLayout_12)
        self.cb_set_best_sol = QtGui.QCheckBox(self.groupBox_8)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_set_best_sol.setFont(font)
        self.cb_set_best_sol.setObjectName(_fromUtf8("cb_set_best_sol"))
        self.verticalLayout_20.addWidget(self.cb_set_best_sol)
        self.verticalLayout_10.addWidget(self.groupBox_8)
        self.g_box_isim = QtGui.QGroupBox(self.tab3)
        self.g_box_isim.setEnabled(True)
        self.g_box_isim.setObjectName(_fromUtf8("g_box_isim"))
        self.verticalLayout_21 = QtGui.QVBoxLayout(self.g_box_isim)
        self.verticalLayout_21.setObjectName(_fromUtf8("verticalLayout_21"))
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.label_23 = QtGui.QLabel(self.g_box_isim)
        self.label_23.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label_23.setFont(font)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_8.addWidget(self.label_23)
        self.sb_isim_rel_step = QtGui.QDoubleSpinBox(self.g_box_isim)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.sb_isim_rel_step.setFont(font)
        self.sb_isim_rel_step.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        self.sb_isim_rel_step.setDecimals(2)
        self.sb_isim_rel_step.setMinimum(0.25)
        self.sb_isim_rel_step.setMaximum(100.0)
        self.sb_isim_rel_step.setSingleStep(0.25)
        self.sb_isim_rel_step.setObjectName(_fromUtf8("sb_isim_rel_step"))
        self.horizontalLayout_8.addWidget(self.sb_isim_rel_step)
        self.verticalLayout_18.addLayout(self.horizontalLayout_8)
        self.cb_use_isim = QtGui.QCheckBox(self.g_box_isim)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.cb_use_isim.setFont(font)
        self.cb_use_isim.setObjectName(_fromUtf8("cb_use_isim"))
        self.verticalLayout_18.addWidget(self.cb_use_isim)
        self.verticalLayout_21.addLayout(self.verticalLayout_18)
        self.verticalLayout_10.addWidget(self.g_box_isim)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem1)
        self.tabWidget.addTab(self.tab3, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        Form.setWindowTitle(_translate("Form", "Ocelot Interface", None))
        self.pb_start_scan.setText(_translate("Form", "Start optimization", None))
        self.pb_logbook.setText(_translate("Form", "Logbook", None))
        self.pb_help.setText(_translate("Form", "Help/Docs", None))
        self.pushButton_3.setText(_translate("Form", "GP 2D Heatmap", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Optimization Scan Panel", None))
        self.label_3.setText(_translate("Form", "Scanner Setup and Options Panel", None))
        self.groupBox.setTitle(_translate("Form", "Scanner Timing", None))
        self.label_2.setText(_translate("Form", "Trim Delay (seconds)          ", None))
        self.label_6.setText(_translate("Form", "Interval between readings (seconds)", None))
        self.label_30.setText(_translate("Form", "Number of readings", None))
        self.label_7.setText(_translate("Form", "Cycle Period = ", None))
        self.groupBox_2.setTitle(_translate("Form", "GP Scanner Setup", None))
        self.label_9.setText(_translate("Form", "GP Hyperparameter FIle     ", None))
        self.label_8.setText(_translate("Form", "GP Seed File", None))
        self.label_10.setText(_translate("Form", "Iterations of Seed", None))
        self.pb_hyper_file.setText(_translate("Form", "HyperFile", None))
        self.cb_use_live_seed.setText(_translate("Form", "Use Live Simplex Seed Mode", None))
        self.groupBox_5.setTitle(_translate("Form", "Configuration Files", None))
        self.pb_save_as.setText(_translate("Form", "Save As", None))
        self.pb_load.setText(_translate("Form", "Load", None))
        self.pb_rewrite.setText(_translate("Form", "Rewrite Default", None))
        self.groupBox_4.setTitle(_translate("Form", "Simplex/Scipy Scanner Setup", None))
        self.checkBox_2.setText(_translate("Form", "Use Normalization File", None))
        self.label_11.setText(_translate("Form", "Normalization Scaling Coeff", None))
        self.pushButton_4.setText(_translate("Form", "Dev Ocelot Epics Panel", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab2), _translate("Form", "Scan Setup Panel", None))
        self.label_18.setText(_translate("Form", "Objective and Alarm Function Setup", None))
        self.groupBox_7.setTitle(_translate("Form", "Objective Function", None))
        self.pb_edit_obj_func.setText(_translate("Form", "Edit Objective Function", None))
        self.cb_use_predef.setText(_translate("Form", "Use Predefined Objective Function", None))
        self.le_obf.setText(_translate("Form", "A", None))
        self.label_16.setText(_translate("Form", "PV: A", None))
        self.label_19.setText(_translate("Form", "PV: B", None))
        self.label_20.setText(_translate("Form", "PV: C", None))
        self.label_28.setText(_translate("Form", "PV: D", None))
        self.label_29.setText(_translate("Form", "PV: E", None))
        self.label_21.setText(_translate("Form", "Objective Function:", None))
        self.label_26.setText(_translate("Form", "Max Penalty", None))
        self.groupBox_6.setTitle(_translate("Form", "Machine Status", None))
        self.label_13.setText(_translate("Form", "Alarm 1", None))
        self.label_14.setText(_translate("Form", "Limits:     ", None))
        self.label_15.setText(_translate("Form", "Wait", None))
        self.label_12.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">Value:    </span></p></body></html>", None))
        self.label_alarm.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:16pt;\">0</span></p></body></html>", None))
        self.label_17.setText(_translate("Form", "Min   ", None))
        self.label_22.setText(_translate("Form", "          Max    ", None))
        self.label_24.setText(_translate("Form", "sec after recovering                             ", None))
        self.groupBox_8.setTitle(_translate("Form", "Scanner Parameters", None))
        self.label_27.setText(_translate("Form", "Select Optimiser Algorithm ", None))
        self.label_25.setText(_translate("Form", "Number Iterations", None))
        self.cb_set_best_sol.setText(_translate("Form", "Set Best Solution After Optimization", None))
        self.g_box_isim.setTitle(_translate("Form", "Simplex/Scipy Scanner Setup", None))
        self.label_23.setText(_translate("Form", "Relative Step in %", None))
        self.cb_use_isim.setText(_translate("Form", "Use Initial Simplex/Step [step =(Max - Min) x RelStep[%]]", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab3), _translate("Form", "Objective Function", None))

from resetpanel.resetpanelbox import ResetpanelBoxWindow
